### ISSUE TITLE
Updating the framework lists

### ISSUE THREAD

**Issue by efrj** [neiesc/awesome-minimalist#169]
Reviewing the lists, I discovered that some frameworks are no longer available and others have links to their documentation pages changed.
I want to make the corrections by changing the links and removing some items.
Do I need to create a branch for these changes or can I use the master branch?

**Comment by neiesc** [comment]
Could be using the master branch and making a Pull request.

**Comment by neiesc** [comment]
@efrj ?

**Comment by neiesc** [comment]
I'm close this issue, because along years ago
