### ISSUE TITLE
Get on awesome lists

### ISSUE THREAD

**Issue by neiesc** [neiesc/awesome-minimalist#185]
https://github.com/sindresorhus/awesome/pull/1892

PR Review:
- https://github.com/sindresorhus/awesome/pull/1886#issuecomment-720178872
- https://github.com/sindresorhus/awesome/pull/1919#issuecomment-744684106

**Comment by Jogai** [comment]
How's this coming along? Need help?

**Comment by neiesc** [comment]
Hi, currently no, thanks. I'm block all pr because of conflicts

**Comment by neiesc** [comment]
@Jogai Hi, currently no, thanks. I'm block all pr for avoid conflicts.
