### ISSUE TITLE
Replace the sizes from npm packages with a shield

### ISSUE THREAD

**Issue by Jogai** [neiesc/awesome-minimalist#188]
Some say nothing, some mention minified/gzipped and probably a lot are outdated. In my opinion it would be better to use the bundlephobia shield:

![zipped-size](https://img.shields.io/bundlephobia/minzip/wingcss?style=for-the-badge)

And maybe something to indicate how up-to-date the library is:

![last-commit](https://img.shields.io/github/last-commit/kbrsh/wing?style=for-the-badge)

**Comment by neiesc** [comment]
It's awesome, thanks for suggests, currently I'm work in transforms table in a list I'll test this.

**Comment by Jogai** [comment]
I used [badgen](https://badgen.net/) here: https://github.com/Jogai/You-Dont-Need-Momentjs/tree/patch-1
The badges are a bit smaller, maybe that looks better.

**Comment by neiesc** [comment]
@Jogai Hi sorry I not notificated  this message. you repo is off.
![Screenshot from 2021-02-22 16-09-27](https://user-images.githubusercontent.com/251643/108757521-b2923500-7528-11eb-8b30-eff5610d4418.png)

**Comment by Jogai** [comment]
Oh, they accepted my PR so you can see the result in the official repo: https://github.com/you-dont-need/You-Dont-Need-Momentjs

**Comment by Jogai** [comment]
Awesome work!
